# Site settings
title: "Your Site Title"
description: "A brief description of your site for SEO purposes."
baseurl: "" # Leave empty for personal GitHub Pages; use "/project-name" for a project page
url: "https://javed.chitaman.github.io" # Your GitHub Pages URL without a trailing slash

# Author details
author: "Javed M. Chitaman, Ph.D."
email: "jchitaman@gmail.com"
location: "Philadelphia, PA"

# Theme settings
remote_theme: ngzhio/jekyll-theme-hamilton
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


# Skins and Styles
skin: "daylight" # Choose from daylight, midnight, sunrise, or sunset
lang: "en" # Language setting for the site
paginate: 5 # Number of posts per page
date_format: "%b %-d, %Y" # Date format

# MathJax and Table of Contents
# Enable MathJax and TOC on specific pages by adding `math: true` and `toc: true` in their front matter

# Sitemap
sitemap:
  changefreq: weekly
  priority: 1.0

# SEO
seo:
  title: "Your Site Title"
  description: "A description of your site for search engines."

# Archives configuration (for categories, tags, etc.)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true # Automatically enable TOC on posts
